### ISSUE TITLE
BackgroundImage missing when legend is inactive

### ISSUE THREAD

**Issue by lwl0812** [shichuanpo/vcytoscape#2]
Expected:
![image](https://user-images.githubusercontent.com/15256957/81137125-3f670480-8f90-11ea-8d2d-a539e3f8adba.png)

Result:
![image](https://user-images.githubusercontent.com/15256957/81137134-4726a900-8f90-11ea-9cff-b7a8da744d7c.png)

Hope to fixed this, tks!

**Comment by shichuanpo** [comment]
This has been resolved in new version
