### ISSUE TITLE
在node上添加标签，用cytoscape-node-html-label如何优雅集成

### ISSUE THREAD

**Issue by aMiing** [shichuanpo/vcytoscape#7]
想要在node上添加标签，重点标注，和cytoscape-node-html-label如何优雅集成，或者还有什么更好的方案？

**Comment by shichuanpo** [comment]
> 想要在node上添加标签，重点标注，和cytoscape-node-html-label如何优雅集成，或者还有什么更好的方案？
var nodeHtmlLabel = require('cytoscape-node-html-label');
Vue.use(vcytoscape, {
    beforeCreate: (Cytoscape) => { // inject plugin for cytoscape
      nodeHtmlLabel( Cytoscape ); // register extension
    }
});
